language: c

cache: ccache

compiler:
  - gcc
  - clang

sudo: required
dist: bionic

matrix:
  include:
    - compiler: gcc
      env: ANALYZE=true

addons:
    apt:
        packages:
        - cppcheck
        - libsdl2-dev
        - libsdl2-mixer-dev
        - libsdl2-net-dev
        - libsdl2-image-dev

script: ./.travis.sh

branches:
    only:
    - master
    - development
